# Generated by Django 4.2.9 on 2025-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
